### ISSUE TITLE
Use proper particle-laser interaction operator

### ISSUE THREAD

**Issue by tbpedersen** [Schoyen/quantum-systems#39]
The interaction ("time evolution") operator defined by the class LaserPulse has the wrong sign. The interaction operator is properly defined as (in the electric-dipole approximation)

 V(t) = -**d** . **E**(t)

where **E**(t) is the electric field vector amplitude (incl. envelope) and **d** is the dipole moment operator defined (for electrons, in a.u.) as

 **d** = -**r**

where **r** is the position operator.

**Comment by tbpedersen** [comment]
The proper class name is LaserField (not LaserPulse....)

**Comment by Schoyen** [comment]
It is apparently long overdue to fix the sign of the dipole moment integrals, ref. #8, #19. I think a solution where we introduce a `charge`-parameter to the basis sets would be most clear. We can then define `position` as the current `dipole_moment` and instead let `dipole_moment = charge * position` as a new definition. Note that this will probably break quite a lot of downstream code/tests as the sign of the induced dipole moment will switch.

Regarding the last [comment](https://github.com/Schoyen/quantum-systems/issues/39#issuecomment-604884624), perhaps a better name for the `LaserField`-operator ([here](https://github.com/Schoyen/quantum-systems/blob/master/quantum_systems/time_evolution_operators/operator.py#L79)) would be `ElectricDipoleInteraction` and an argument to the class would be named  `electric_field` instead of `laser_pulse`? This might also avoid some confusion as to the applicability of the operator considering that it is not strictly limited to a "laser field", but rather any electric field in the dipole approximation. Furthermore, the sign of the addition of the interaction and the one-body Hamiltonian should be replaced by a subtraction ([here](https://github.com/Schoyen/quantum-systems/blob/master/quantum_systems/time_evolution_operators/operator.py#L104)).

I'll try to get a pull request ready with a proposal for a solution today.
